// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

// import { ThemeProvider } from "@mui/material/styles";
// import CssBaseline from "@mui/material/CssBaseline";
// import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
// import theme from "../theme/theme";
// // import { AuthProvider } from "@/context/AuthContext";
// import { AuthProvider } from "../context/AuthContext";

// export const metadata = {
//   title: "Kids Meal Subscription",
//   description: "Healthy meals delivered to your child's school",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>
//         <AppRouterCacheProvider>
//           <ThemeProvider theme={theme}>
//             <CssBaseline />
//             <AuthProvider>{children}</AuthProvider>
//           </ThemeProvider>
//         </AppRouterCacheProvider>
//       </body>
//     </html>
//   );
// }

import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import CssBaseline from "@mui/material/CssBaseline";
import "./globals.css";
import { Providers } from "./providers";

export const metadata = {
  title: "Kids Meal Subscription",
  description: "Healthy meals delivered to your child's school",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <Providers>
            <CssBaseline />
            {children}
          </Providers>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
